---
- name: Run command on both routers
  hosts: Routers, Switches
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Run 'show arp' on both routers and the switch
      ios_command:
        commands:
          - show arp
      register: output

    - name: Display command output
      debug:
        var: output.stdout_lines

